
package stub.br.com.clean.architecture.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.clean.architecture.service.Empregado;
import br.com.clean.architecture.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpregadoService", targetNamespace = "http://service.architecture.clean.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpregadoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.clean.architecture.service.Empregado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmpregado", targetNamespace = "http://service.architecture.clean.com.br/", className = "br.com.clean.architecture.service.GetEmpregado")
    @ResponseWrapper(localName = "getEmpregadoResponse", targetNamespace = "http://service.architecture.clean.com.br/", className = "br.com.clean.architecture.service.GetEmpregadoResponse")
    @Action(input = "http://service.architecture.clean.com.br/EmpregadoService/getEmpregadoRequest", output = "http://service.architecture.clean.com.br/EmpregadoService/getEmpregadoResponse")
    public Empregado getEmpregado(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns br.com.clean.architecture.service.Empregado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmpregado", targetNamespace = "http://service.architecture.clean.com.br/", className = "br.com.clean.architecture.service.UpdateEmpregado")
    @ResponseWrapper(localName = "updateEmpregadoResponse", targetNamespace = "http://service.architecture.clean.com.br/", className = "br.com.clean.architecture.service.UpdateEmpregadoResponse")
    @Action(input = "http://service.architecture.clean.com.br/EmpregadoService/updateEmpregadoRequest", output = "http://service.architecture.clean.com.br/EmpregadoService/updateEmpregadoResponse")
    public Empregado updateEmpregado(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmpregado", targetNamespace = "http://service.architecture.clean.com.br/", className = "br.com.clean.architecture.service.DeleteEmpregado")
    @ResponseWrapper(localName = "deleteEmpregadoResponse", targetNamespace = "http://service.architecture.clean.com.br/", className = "br.com.clean.architecture.service.DeleteEmpregadoResponse")
    @Action(input = "http://service.architecture.clean.com.br/EmpregadoService/deleteEmpregadoRequest", output = "http://service.architecture.clean.com.br/EmpregadoService/deleteEmpregadoResponse")
    public boolean deleteEmpregado(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns br.com.clean.architecture.service.Empregado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmpregado", targetNamespace = "http://service.architecture.clean.com.br/", className = "br.com.clean.architecture.service.AddEmpregado")
    @ResponseWrapper(localName = "addEmpregadoResponse", targetNamespace = "http://service.architecture.clean.com.br/", className = "br.com.clean.architecture.service.AddEmpregadoResponse")
    @Action(input = "http://service.architecture.clean.com.br/EmpregadoService/addEmpregadoRequest", output = "http://service.architecture.clean.com.br/EmpregadoService/addEmpregadoResponse")
    public Empregado addEmpregado(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
