micronaut:
  application:
    name: intro-micronaut

address:
  city: Italy

license_plate: CGF8987

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    packages-to-scan:
      - 'intro.micronaut.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

rabbitmq:
  host: localhost
  port: 5672
  username: teste
  password: teste

endpoints:
  flyway:
    enabled: true
    sensitive: false

flyway:
  datasources:
    default:
      locations: classpath:databasemigrations